jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: ['7.0', '7.1', '7.2', '7.3', '7.4', '8.0', '8.1']
        phpunit-version: ['9.5.0']
    name: PHPUnit ${{ matrix.phpunit-version }} on PHP ${{ matrix.php-version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
      - name: Install
        run: |
          composer require phpunit/phpunit:${{ matrix.phpunit-version }}
          composer require squizlabs/php_codesniffer
          composer require phpmd/phpmd
      - name: PHPUnit
        run: vendor/bin/phpunit
      - name: PHPCS
        run: vendor/bin/phpcs --standard=PSR2 classes/ tests/
      - name: PHPMD
        run: vendor/bin/phpmd classes/ text cleancode,codesize,controversial,design,naming,unusedcode
